CREATE TABLE IF NOT EXISTS books (
	ID_ bigint(20) NOT NULL AUTO_INCREMENT,
	PUBLISHING_COMPANY VARCHAR(30) NOT NULL,
	TITLE VARCHAR(30) NOT NULL,"
	ISBN VARCHAR(50) NOT NULL,"
	PRIMARY_KEY ('ID')"
);